layout_spectrum: 0.17457638858513225
typography_spectrum: 0.5804812108219075
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.4014914758134597
  lightness: 0.04169759708926967
  saturation: 0.2080027699350647
  rhythmicContrast: 0.21005102488857758
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: SCRUMCULT.org
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SCRUMCULT
content: []
description: Agile for a better world!
purpose: []
url: 'http://www.scrumcult.org'
author:
  name: Jerome Schuit
  email: jerome.schuit@scrumcult.org
  url: 'http://www.scrumcult.org'
github: true
